-- Generated by Oracle SQL Developer Data Modeler 21.2.0.183.1957
--   at:        2021-12-17 11:17:55 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE detalii_reteta (
    denumire_comuna          VARCHAR2(30) NOT NULL,
    forma_farmaceutica       VARCHAR2(10) NOT NULL,
    concentratie             VARCHAR2(10) NOT NULL,
    doza_zilnica             VARCHAR2(10) NOT NULL,
    cantitate                NUMBER(3) NOT NULL,
    nr_zile_tratament        NUMBER(3) NOT NULL,
    pretrf                   NUMBER(3) NOT NULL,
    medicament_id_medicament NUMBER(30) NOT NULL,
    reteta_serie             CHAR(6) NOT NULL,
    reteta_numar             NUMBER(30) NOT NULL
);

ALTER TABLE detalii_reteta
    ADD CONSTRAINT form_farm_ck CHECK ( forma_farmaceutica IN ( 'CAPS', 'COMPR', 'COMPR_FILM', 'SOL_INJ' ) );

ALTER TABLE detalii_reteta ADD CONSTRAINT cantitate_ck CHECK ( cantitate > 1 );

ALTER TABLE detalii_reteta ADD CONSTRAINT nrzile_ck CHECK ( nr_zile_tratament > 1 );

COMMENT ON COLUMN detalii_reteta.denumire_comuna IS
    'DCI = denumirea comună internationala (denumire substanta activa)';

COMMENT ON COLUMN detalii_reteta.pretrf IS
    'Procentul de compensare';

CREATE TABLE diagnostic (
    cod_diagnostic NUMBER(3) NOT NULL,
    tip_diagnostic CHAR(1) NOT NULL
);

ALTER TABLE diagnostic
    ADD CONSTRAINT tip_diagnostic_ck CHECK ( tip_diagnostic IN ( 'A', 'C', 'S' ) );

ALTER TABLE diagnostic ADD CONSTRAINT diagnostic_pk PRIMARY KEY ( cod_diagnostic );

CREATE TABLE info_pacient (
    data_nasterii     DATE NOT NULL,
    sexul             CHAR(1) NOT NULL,
    cetatenia         CHAR(2) NOT NULL,
    categorie_pacient CHAR(3) NOT NULL,
    pacient_cnp       CHAR(13) NOT NULL
);

ALTER TABLE info_pacient
    ADD CONSTRAINT sexul_ck CHECK ( sexul IN ( 'F', 'M' ) );

ALTER TABLE info_pacient
    ADD CONSTRAINT cetatenia_ck CHECK ( cetatenia IN ( 'PO', 'RO', 'US' ) );

ALTER TABLE info_pacient
    ADD CONSTRAINT categorie_pc_ck CHECK ( categorie_pacient IN ( 'AJ', 'ES', 'H', 'LP', 'P',
                                                                  'SAL', 'VET' ) );

CREATE UNIQUE INDEX info_pacient__idx ON
    info_pacient (
        pacient_cnp
    ASC );

CREATE TABLE medicament (
    denumire_comerciala       VARCHAR2(30) NOT NULL,
    id_medicament             NUMBER(30) NOT NULL,
    diagnostic_cod_diagnostic NUMBER(3) NOT NULL
);

ALTER TABLE medicament ADD CONSTRAINT medicament_pk PRIMARY KEY ( id_medicament );

CREATE TABLE pacient (
    nume    VARCHAR2(20) NOT NULL,
    prenume VARCHAR2(20) NOT NULL,
    cnp     CHAR(13) NOT NULL
);

ALTER TABLE pacient ADD CONSTRAINT pacient_pk PRIMARY KEY ( cnp );

CREATE TABLE reteta (
    serie                CHAR(6) NOT NULL,
    numar                NUMBER(30) NOT NULL,
    data_prescrierii     DATE NOT NULL,
    unitate_medicala_cui NUMBER(8) NOT NULL,
    pacient_cnp          CHAR(13) NOT NULL
);

ALTER TABLE reteta ADD CONSTRAINT reteta_pk PRIMARY KEY ( serie,
                                                          numar );

CREATE TABLE unitate_medicala (
    denumire    VARCHAR2(100) NOT NULL,
    adresa      VARCHAR2(150) NOT NULL,
    cui         NUMBER(8) NOT NULL,
    tip_unitate VARCHAR2(3) NOT NULL,
    telefon     NUMBER(13) NOT NULL,
    email_medic VARCHAR2(70) NOT NULL
);

ALTER TABLE unitate_medicala
    ADD CONSTRAINT tip_unitate_ck CHECK ( tip_unitate IN ( 'ALT', 'AMB', 'MF', 'MM', 'SP' ) );

COMMENT ON COLUMN unitate_medicala.cui IS
    'CUI = Cheie unica de inregistrare';

ALTER TABLE unitate_medicala ADD CONSTRAINT unitate_medicala_pk PRIMARY KEY ( cui );

ALTER TABLE detalii_reteta
    ADD CONSTRAINT detalii_reteta_medicament_fk FOREIGN KEY ( medicament_id_medicament )
        REFERENCES medicament ( id_medicament );

ALTER TABLE detalii_reteta
    ADD CONSTRAINT detalii_reteta_reteta_fk FOREIGN KEY ( reteta_serie,
                                                          reteta_numar )
        REFERENCES reteta ( serie,
                            numar );

ALTER TABLE info_pacient
    ADD CONSTRAINT info_pacient_pacient_fk FOREIGN KEY ( pacient_cnp )
        REFERENCES pacient ( cnp );

ALTER TABLE medicament
    ADD CONSTRAINT medicament_diagnostic_fk FOREIGN KEY ( diagnostic_cod_diagnostic )
        REFERENCES diagnostic ( cod_diagnostic );

ALTER TABLE reteta
    ADD CONSTRAINT reteta_pacient_fk FOREIGN KEY ( pacient_cnp )
        REFERENCES pacient ( cnp );

ALTER TABLE reteta
    ADD CONSTRAINT reteta_unitate_medicala_fk FOREIGN KEY ( unitate_medicala_cui )
        REFERENCES unitate_medicala ( cui );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             1
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
